server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${LOCAL_ENV_AUTH_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:58318/user_db}
    username: ${LOCAL_ENV_AUTH_DATASOURCE_USERNAME:appuser}
    password: ${LOCAL_ENV_AUTH_DATASOURCE_PASSWORD:Password@123}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  data:
    redis:
      host: ${LOCAL_SPRING_DATA_REDIS_HOST:127.0.0.1}
      port: ${LOCAL_SPRING_DATA_REDIS_PORT:6379}
      password: ${LOCAL_SPRING_DATA_REDIS_PASSWORD:}
      timeout: 2s

management:
  health:
    redis:
      enabled: false

logging:
  level:
    root: INFO
    com.electrahub.identity: DEBUG
    liquibase: INFO

app:
  user-service:
    base-url: ${LOCAL_APP_USER_SERVICE_BASE_URL:http://127.0.0.1:8082}
  security:
    jwt:
      refresh-token-ttl-days: ${APP_SECURITY_JWT_REFRESH_TOKEN_TTL_DAYS:30}
    oauth:
      google:
        enabled: ${APP_SECURITY_OAUTH_GOOGLE_ENABLED:false}
        issuer: ${APP_SECURITY_OAUTH_GOOGLE_ISSUER:https://accounts.google.com}
        jwk-set-uri: ${APP_SECURITY_OAUTH_GOOGLE_JWK_SET_URI:https://www.googleapis.com/oauth2/v3/certs}
        audiences: ${APP_SECURITY_OAUTH_GOOGLE_AUDIENCES:}
        auto-provision-users: ${APP_SECURITY_OAUTH_GOOGLE_AUTO_PROVISION_USERS:true}
